### ISSUE TITLE
blender files

### ISSUE THREAD

**Issue by yggs1401** [facebookresearch/NSVF#11]
Hello! Can you provide the .blend files for Synthetic-NSVF? Thank you and stay safe!

**Comment by MultiPath** [comment]
Hi, you should be able to download the original blender files following these sites:
– Wineholder(CC-0) https://www.blendswap.com/blend/15899
– Steamtrain(CC-BY-NC) https://www.blendswap.com/blend/16763
– Toad(CC-0) https://www.blendswap.com/blend/13078
– Robot(CC-BY-SA) https://www.blendswap.com/blend/10597
– Bike(CC-BY) https://www.blendswap.com/blend/8850
– Palace(CC-BY-NC-SA) https://www.blendswap.com/blend/14878
– Spaceship(CC-BY) https://www.blendswap.com/blend/5349
– Lifestyle(CC-BY) https://www.blendswap.com/blend/8909
