### ISSUE TITLE
Build my own dataset for training

### ISSUE THREAD

**Issue by zrw97402** [facebookresearch/NSVF#15]
Thanks for your excellent work first.
I'm working on my own dataset for free-viewpoint rendering and interested in your work. Since rgb, pose and intrinsic datas are prepared, how can I get the bbox data like the  style in your datasets?

**Comment by MultiPath** [comment]
The bounding box is usually roughly estimated. For example, if you have the object mask, it is possible to run algorithm like visualhull to get the rough geometry. You can also assign a unit bounding box if you know the object's rough size.

**Comment by zrw97402** [comment]
Thanks for your answer. My target dataset is the open scenes such as a basketball game without a fixed boundary. I wonder if these can be constrainted into such a bbox since some values are unknown and uncertain.

**Comment by MultiPath** [comment]
It would be quite challenging to model unbounded scenes with the current version of NSVF. Since we are basically based on voxels and will prune them during training. So it currently only works in Euclidean space. For large unbounded scenes, it would very inefficient to work in such scenes. I would be interested in how it will look like.

**Comment by zrw97402** [comment]
I've got your words. Thank you.

**Comment by dwangxxx** [comment]
> It would be quite challenging to model unbounded scenes with the current version of NSVF. Since we are basically based on voxels and will prune them during training. So it currently only works in Euclidean space. For large unbounded scenes, it would very inefficient to work in such scenes. I would be interested in how it will look like.

Hello, I've read your paper recently! It's an excellent work. But I have some questions about the details. In the training stage, the voxels are pruned to get more accurate voxels. I want to know if the pruned voxel are applied int the inference stage? Look forward your apply! Thank you!
