### ISSUE TITLE
Dockerfile to build and containerize NSVF

### ISSUE THREAD

**Issue by Misterdudeman** [facebookresearch/NSVF#26]
I would like to run NSVF as a container with a dockerfile.

I started building my own but am having trouble building the project inside an nvidia docker container as I'm using WSL2 and the current build doesn't come with NVCC or debug tools to check the output.

I think the build scripts and Dockerfiles should match the build workflow for Alicevision Meshroom. https://github.com/alicevision/meshroom/tree/develop/docker

I still need to build the build-ubuntu.sh script but any help or info on building this cleanly would be appreciated.

```ARG CUDA_VERSION
ARG UBUNTU_VERSION
ARG COMMAND

FROM nvidia/cuda:${CUDA_VERSION}-devel-ubuntu${UBUNTU_VERSION}
COPY . /NVSF/
WORKDIR /NVSF
RUN apt-get update \
  && apt-get install -y python3-pip python3 git \
  && cd /usr/local/bin \
  && ln -s /usr/bin/python3 python \
  && pip3 install --upgrade pip \
  && pip3 install torch \
  && pip3 install -r /NVSF/requirements.txt
CMD /bin/bash ${COMMAND}
```

**Comment by MultiPath** [comment]
I don't have experience of building dockerfile. I can take a look to see how to do that if I have time but I am not too sure.

**Comment by Misterdudeman** [comment]
I'll give it another go and let you know how it turns out.
