### ISSUE TITLE
Query: raymarching_tolerance and BackgroundField

### ISSUE THREAD

**Issue by nitthilan** [facebookresearch/NSVF#28]
raymarching_tolerance - Is this field used only during rendering? Can this be used while training too? i.e. reduce the number of steps to accumulate the sigma value?

Is the BackgroundField used during training? I do not see it being used. How is the background color taken care of during the training process

**Comment by MultiPath** [comment]
Hi, we turned off tolerance during training. It is definitely possible to turn it on to speed up training but it may potentially hurt performance.
The backgroundfield is set to output the background color.

**Comment by nitthilan** [comment]
Hi, 
When you say hurt performance, what exactly do you mean? Would it not encode data properly?

Further, why is there a Field for Background. It is just a single color and so could be hardcoded right? What is the significance of using a NN to approximate the BG?

**Comment by MultiPath** [comment]
Currently it the code in the master branch did not work for complicated background other than single color (like white). It was saved for future development.

I just guess it would hurt performance. As early stop means it will end the ray marching early before go through all voxels. So the remaining voxels will be ignored without any gradients

**Comment by nitthilan** [comment]
Thanks for the explanation. I see the value used for raymarching_tolerance is set to 0.01 for some sequences. 
Taking log base e it gives a value of 4.6. What is the significance of this value for sigma?

Just curious about how you plan to separate foreground and background objects. Is the idea to encode everything outside the bounding box as background?

**Comment by MultiPath** [comment]
Hi, 0.01 it means when the accumulated probability along the ray reaches 99%, it will early terminate and stop evaluating the rest
