### ISSUE TITLE
Could u guys share the pose export script in Blender?

### ISSUE THREAD

**Issue by yumi-cn** [facebookresearch/NSVF#36]
I already try to export the pose in blender by myself in the recent two weeks.

But I find some issues about the process:

- First, when I used the codes, which similar to the script shared by the Nerf team, to export the poses of cameras, I found that all rays miss voxels in NSVF train codes(cause Error), which means that all rays goes the wrong direction, I try to deepinto the codes and debug to figure out why or what cause the problem,  and I found that the defaut direction of the camera in blender is pointed to negative z-axis, which means this is conflict with the codes of NSVF, NSVF train codes set the default depth to 1 at ray direction calculating stage(in blender the camera imaging depth is -1 due to negative z-axis)，and this cause all ray direction point to the opposition and so miss all voxels.

- Second, I check the pose data of same model between Nerf and NSVF, and I found that the pose(cam2world matrix) at the second/third cols is different from the nerf data(nsvf those two cols multi -1 turn into nerf data)，this maybe an evidence to the depth setting problem just mentioned at the first part.

- After I fix the depth bugs of depth setting, train codes run normally, but compared to the official data shared by NSVF, my results are no good enough, and in valid part, all images someway fall into a malposition problem(lead to very high valid loss problem), which I also try to debug and understand the problems for some days, and I still do not get the good results in my all trys.

So, can u guys share the export scripts in blender? or other 3D model application?

**Comment by yumi-cn** [comment]
And how you guys calculate the intrinsics data in blender?

Especially the the focal len in pixel dimension, how to transform the focal len  from mm to pixel?

For example, the focal len is 50mm, sensor size is 36mm*36mm, resolution 800*800, what is the focal len in intrinsics.txt, in my calculate method, result is 800pix * 50mm / 36mm = 1111.111111111111, Is this correct for nsvf codes?

**Comment by MultiPath** [comment]
I will put the scripts we used in the next 1-2 days.  Yes, I think we used a OpenCV style camera, which is different from NeRF which I believe it was based on OpenGL?

**Comment by yumi-cn** [comment]
> I will put the scripts we used in the next 1-2 days. Yes, I think we used a OpenCV style camera, which is different from NeRF which I believe it was based on OpenGL?

Nice! thanks.

**Comment by MultiPath** [comment]
Hi @yumi-cn  Sorry for being late here. I recently updated the code and there is an example script to create new data with blender. It works fine on my win10 laptop. I also added a blender file in the folder for reference (you might need to add your own HDR image if you want a different lighting result)

https://github.com/facebookresearch/NSVF/blob/master/examples/data/render_example.bat
