### ISSUE TITLE
cannot use with Rtx3090 GPU

### ISSUE THREAD

**Issue by stephane2017hongkong** [facebookresearch/NSVF#45]
**Describe the bug**
if using PyTorch 1.4 and Cuda 10.2, then Rtx3090 is not supported (RTX 3090 is using compute 8.6)
if trying with PyTorch 1.71 and Cuda 11.0 then fairnr does not compile
(ValueError: Unknown CUDA arch (8.6) or GPU not supported)

**To Reproduce**
1 - install all recommended dependancies as explained in Readme.md

**Expected behavior**
As NSVF is about fast rendering it would be great to have it working on latest Nvidia's flagship GPU.

**Desktop (please complete the following information):**
 - Using Conda 
 - OS:  Ubuntu 20.04
 - Driver Version: 460.32.03    CUDA Version: 11.2

**Comment by peschn** [comment]
I am using nsvf with 2 rtx3090 and it works fine. But the difference is, that I am using CUDA 11.1. I installed pytorch with the following command: pip install torch==1.7.1+cu110 -f https://download.pytorch.org/whl/torch_stable.html

Did you test you CUDA installation, does it work? What is the output if you run `nvidia-smi`?

**Comment by stephane2017hongkong** [comment]
Thank you for this detailed info, it helped me to sort it out.
