### ISSUE TITLE
question about the dynamic scene

### ISSUE THREAD

**Issue by zdw-qingdao** [facebookresearch/NSVF#51]
I don't really understand how to get the results of a dynamic scene.
What's the meaning of 'hypernetwork to encode all the 200 frames'?

![Screenshot from 2021-06-04 19-21-10](https://user-images.githubusercontent.com/41947948/120793925-1980aa80-c56a-11eb-
8da8-6ab349152f03.png)

Hope to know the specific operation. Thanks a lot!

**Comment by MultiPath** [comment]
Hi, the dynamic scene part is not open-sourced in this version of code and that is quite messy. We have a improved version for dynamic scenes which will be open-source later. Thanks
