### ISSUE TITLE
AttributeError: module 'fairnr' has no attribute 'clib'

### ISSUE THREAD

**Issue by dtseng** [facebookresearch/NSVF#57]
I'm having trouble running the training scripts after installing the repo. 

I've followed the steps: 
```
pip install -r requirements.txt
pip install --editable ./
```
And then tried running `train_wineholder.sh` (I've also tried `python train.py` without arguments)

I get the following error: 
```
Traceback (most recent call last):
  File "train.py", line 7, in <module>
    from fairnr_cli.train import cli_main
  File "/home/david/repos/NSVF/fairnr_cli/train.py", line 26, in <module>
    from fairnr import ResetTrainerException
  File "/home/david/repos/NSVF/fairnr/__init__.py", line 11, in <module>
    from . import data, tasks, models, modules, criterions
  File "/home/david/repos/NSVF/fairnr/data/__init__.py", line 6, in <module>
    from .shape_dataset import (
  File "/home/david/repos/NSVF/fairnr/data/shape_dataset.py", line 14, in <module>
    from . import data_utils, geometry, trajectory
  File "/home/david/repos/NSVF/fairnr/data/geometry.py", line 12, in <module>
    from fairnr.clib._ext import build_octree
  File "/home/david/repos/NSVF/fairnr/clib/__init__.py", line 28, in <module>
    import fairnr.clib._ext as _ext
AttributeError: module 'fairnr' has no attribute 'clib'
```

I didn't have any trouble with running `pip install --editable ./` since I get the following output: 
```
Obtaining file:///home/david/repos/NSVF
Installing collected packages: fairnr
  Running setup.py develop for fairnr
Successfully installed fairnr-0.0.0
```

But looking at the output from running the training scripts, it seems like there's a build issue with `fairnir.clib`, anyone know why? I'm running this on Ubuntu 18.04 with CUDA 10.2. (Also tried CUDA 10.0, get the same error).

**Comment by MultiPath** [comment]
Hi, did you see the compiled files? It should compile these libs to fairnr/clib/
Where are you running your scripts?

**Comment by dtseng** [comment]
Inside the fairnr/clib folder, I see the following: `_ext.cpython-36m-x86_64-linux-gnu.so  include  __init__.py  __pycache__  src`. Is this missing some output libs? 

I'm running from the `NSVF` folder. So within the NSVF folder, I run the following command: `./examples/train/train_wineholder.sh`

**Comment by dtseng** [comment]
Btw, I found the problem. I noticed that someone else had the same issue as me (https://github.com/facebookresearch/NSVF/issues/6). Basically make sure that your python version is at least 3.7+
