### ISSUE TITLE
why to add a 10% bias on x? 

### ISSUE THREAD

**Issue by chensjtu** [facebookresearch/NSVF#60]
in fairnr/modules/encoder.py
line 384
points[:, 0] += (self.voxel_size / 10) # why? move all the x a little right
why do you here add a bias on x? does it affects a lot?

**Comment by MultiPath** [comment]
Hi, I think it will not affect the rendering process, but I could not remember exactly right now..

**Comment by chensjtu** [comment]
Thanks for your kind reply! I'll try to remove the bias and wait for your original insight.

**Comment by chensjtu** [comment]
I think I got it! it is used to avoid -1 when calculate the voxel index!

**Comment by MultiPath** [comment]
Yeah, you reminded me. It was just a hack to solve some bugs in my early development. There should be a better way
