### ISSUE TITLE
NSVF dataset convention

### ISSUE THREAD

**Issue by lalitmanam** [facebookresearch/NSVF#64]
Thanks for sharing the datasets.

Could you provide the following conventions for the NSVF dataset?
1. Coordinate convention for the axes? I.e. direction of +x (left /right), +y (up or down), +z( forward/backward)
2. Camera pose convention: from camera-to-world or world-to-camera

It is not mentioned in the ReadMe file.

**Comment by kwea123** [comment]
For training it's right, down, front and the pose is camera to world.
For `tanks and temples` and `blendedmvs`, there is `test_traj.txt` used to generate testing views. However, the pose axes here are "left down front", which is different from the training pose convention. Took me some time to figure out.

**Comment by lalitmanam** [comment]
This worked! Thank you very much.
